In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
dtype = torch.float
x = torch.linspace(-math.pi, math.pi, 2000, dtype=dtype)
y = torch.sin(x)

In [3]:
p = torch.tensor([1,2,3])
xx = x.unsqueeze(-1).pow(p)

In [4]:
xx

tensor([[ -3.1416,   9.8696, -31.0063],
        [ -3.1384,   9.8499, -30.9133],
        [ -3.1353,   9.8301, -30.8205],
        ...,
        [  3.1353,   9.8301,  30.8205],
        [  3.1384,   9.8499,  30.9133],
        [  3.1416,   9.8696,  31.0063]])

In [5]:
linear_layer = torch.nn.Linear(3, 1)

In [6]:
y_pred = linear_layer(xx)

In [7]:
linear_layer.weight

Parameter containing:
tensor([[-0.4969,  0.2247, -0.0751]], requires_grad=True)

In [8]:
linear_layer.bias

Parameter containing:
tensor([-0.1275], requires_grad=True)

In [10]:
A = linear_layer.weight.detach().numpy()

In [11]:
A

array([[-0.49688318,  0.2246548 , -0.07506669]], dtype=float32)

In [12]:
b = linear_layer.bias.detach().numpy()

In [13]:
b

array([-0.127457], dtype=float32)

In [17]:
x = xx.numpy()

In [18]:
x

array([[ -3.1415927,   9.869605 , -31.006279 ],
       [ -3.1384497,   9.849866 , -30.91331  ],
       [ -3.1353064,   9.830146 , -30.820518 ],
       ...,
       [  3.1353064,   9.830146 ,  30.820518 ],
       [  3.1384494,   9.849865 ,  30.913303 ],
       [  3.1415927,   9.869605 ,  31.006279 ]], dtype=float32)

In [23]:
x.dot(A.T) + b

array([[ 5.97834  ],
       [ 5.965365 ],
       [ 5.9524074],
       ...,
       [-1.7905428],
       [-1.7946397],
       [-1.798746 ]], dtype=float32)

In [24]:
y_pred

tensor([[ 5.9783],
        [ 5.9654],
        [ 5.9524],
        ...,
        [-1.7905],
        [-1.7946],
        [-1.7987]], grad_fn=<AddmmBackward>)