In [3]:
import numpy as np
import matplotlib.pyplot as plt
import math
import torch

In [32]:
t = torch.tensor([[6, 5], [3, 4], [7, 2]])
torch.gather(t, 0, torch.tensor([[1, 2], [2, 1]]))

tensor([[3, 2],
        [7, 4]])

In [53]:
t.max(1).indices

tensor([0, 1, 0])

In [39]:
x = torch.randn(4, 4)

In [49]:
x[3,3]

tensor(1.1936)

In [54]:
x.view(-1,8)

tensor([[-0.5837, -0.5162,  0.7135,  1.7754, -1.6116,  1.3972, -2.0081, -0.4812],
        [-0.8010,  0.2531,  1.0803,  1.0411,  0.4466, -0.4982, -0.0677,  1.1936]])

In [59]:
x.view(16)

tensor([-0.5837, -0.5162,  0.7135,  1.7754, -1.6116,  1.3972, -2.0081, -0.4812,
        -0.8010,  0.2531,  1.0803,  1.0411,  0.4466, -0.4982, -0.0677,  1.1936])